mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 9090
spring:
  application:
    name: tlias-web-mannager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tlias
    username: root
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB
aliyun:
  oss:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    bucketName: web-tlias-mystudy
